spring.application.name=realworld-backend
#server.port=8081
# 数据源配置
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/realworld?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#spring.datasource.url=jdbc:mysql://mysql-demo:3306/你的数据库名?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=123456

# MyBatis Plus 配置
mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml
mybatis-plus.type-aliases-package=com.realworld.blog.entity

# 打印 SQL 日志（方便调试）
logging.level.com.yourcompany.demo.mapper=debug

# 日志配置
logging.level.com.company.demo=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.boot=INFO

# 日志输出格式
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n

# 输出到文件（可选）
logging.file.name=logs/blog.log

# Redis 配置
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=5000ms

# 连接池配置
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

# HikariCP 监控配置
spring.datasource.hikari.register-mbeans=true

# Actuator 端点暴露
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
# 把 localhost 改成 host.docker.internal
#spring.datasource.url=jdbc:mysql://host.docker.internal:3306/test_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8

# 分布式集群部署utils\SnowflakeIdWorker.java
snowflake.worker-id=1
snowflake.datacenter-id=1
## RabbitMQ 配置
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#spring.rabbitmq.virtual-host=/
#
## 消息确认机制
#spring.rabbitmq.publisher-confirm-type=correlated
#spring.rabbitmq.publisher-returns=true
#
## 消费端配置
#spring.rabbitmq.listener.simple.acknowledge-mode=auto
#spring.rabbitmq.listener.simple.concurrency=5
#spring.rabbitmq.listener.simple.max-concurrency=10